### ISSUE TITLE
A valid generated fødselsnummer is not valid according to Nin.IsValid()

### ISSUE THREAD

**Issue by njanor** [slahn/nonin#1]
Creating a Nin with a valid fødselsnummer sometimes fail.

My most recent example, I tried to create a Nin with (the generated) fødselsnummer 03125463265 and it failed. Having checked, this is a valid fødselsnummer (the birth year could be 1854 for instance).

**Comment by slahn** [comment]
Thanks for testing and noticing!
When checking the century, I accidentaly tested the year with `> 54` instead of `>= 54`.
Should be fixed now - could you test and verify?

If you have other cases that fail, please let me know!

**Comment by slahn** [comment]
@njanor Are there any more failing cases you know about?

**Comment by slahn** [comment]
I've pushed a new nuget package with the 1854 bug fixed. Please open a new issue if you have any more examples of failing numbers.

**Comment by njanor** [comment]
Hi,

Sorry that I was unable to test it before you made a new NuGet-package.

However, I have updated it, and all validation errors which used to occur in my test are now gone.

Thank you :)
